---
title: "Data Vizualization Aug 2018 Pilot"
author: "Amelia"
date: "11/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lme4)
library(rstan)
```

Effect of number of data points(100 points-->3600 points) on acoustic distance
```{r efffect of amount of data, echo=FALSE}
data_unfilt<-read.csv("geomphon_pilot_results_for_analysis.csv")

data_unfilt$subject_id<-as.factor(data_unfilt$subject_id)

df<-data.frame(delta_dist_div=c(),N=c())
#create a sequence from 100 to 2900
byhundo<-seq(from =100, to =3600, by = 100)
#repeat that sequence 10 times
mysizes<-rep(byhundo,10)
#for each of those values, run the following loop


for (i in mysizes) {
    data=data_unfilt
    sampdat<-sample_n(data, i, replace= TRUE)
    mod<-glm(user_corr~delta_dist_div, family=binomial, data=sampdat)
    myefs<-coef(mod)
    row<-data.frame(delta_dist_div=unname(myefs[2]),N=i)
    df <- rbind(df,row)
}

library(ggplot2)
df$N<-as.factor(df$N)

p<-ggplot(df, aes(x=N, y=delta_dist_div)) + 
  geom_violin()
p



```

Number of participants vs. Beta estimates for acoustic distance 

```{r betas vs distance}
subjs<-seq(from=2, to=26, by=1)

mysubjs<-rep(subjs,10)
#for each of those values, run the following loop

list_of_subjs<-levels(as.factor(data_unfilt$subject_id))
df2<-data.frame(delta_dist_div=c(),N_subjs=c())


for (i in mysubjs) {
   #sample i people from the list of subject 
    right_subjs<-sample(list_of_subjs,size=i,replace=FALSE)
    #filter only data from people selected above 
    sampdat<-dplyr::filter(data_unfilt,subject_id %in% right_subjs)
    #mod<-glmer(user_corr~delta_dist_div+(1+delta_dist_div|subject), family=binomial, data=sampdat)
    mod<-glm(user_corr~delta_dist_div, family=binomial, data=sampdat)
    #myefs<-fixef(mod)
    myefs <- coef(mod)
    row<-data.frame(delta_dist_div=unname(myefs[2]),N=i)
    df2 <- rbind(df2,row)
}

df2$N<-as.factor(df2$N)

p2<-ggplot(df2, aes(x=N, y=delta_dist_div)) + 
  geom_violin()
p2

```


Number of participants vs. Beta estimates for glob 

```{r beta glob N}

results_2_cross<-read.csv("results_2_cross.csv")


subjs<-seq(from=2, to=length(unique(results_2_cross$subject_id)), by=1)

#repeat that sequence 10 times
mysubjs<-rep(subjs,10)

#for each of those values, run the following loop
list_of_subjs<-levels(as.factor(results_2_cross$subject_id))

#GLOB

df3<-data.frame(glob=c(),N_subjs=c())


for (i in mysubjs) {
   #sample i people from the list of subject 
    right_subjs<-sample(list_of_subjs,size=i,replace=FALSE)
    #filter only data from people selected above 
    sampdat<-dplyr::filter(results_2_cross,subject_id %in% right_subjs)
    #mod<-glmer(user_corr~delta_dist_div+(1+delta_dist_div|subject), family=binomial, data=sampdat)
    mod<-glm(user_corr~glob, family=binomial, data=sampdat)
    #myefs<-fixef(mod)
    myefs <- coef(mod)
    row<-data.frame(glob=unname(myefs[2]),N=i)
    df3 <- rbind(df3,row)
}

df3$N<-as.factor(df3$N)

p3<-ggplot(df3, aes(x=N, y=glob)) + 
  geom_violin()

p3
```

Number of participants vs. Beta estimates for  Var 2 = Loc
```{r N beta loc}


df4<-data.frame(loc=c(),N_subjs=c())


for (i in mysubjs) {
   #sample i people from the list of subject 
    right_subjs<-sample(list_of_subjs,size=i,replace=FALSE)
    #filter only data from people selected above 
    sampdat<-dplyr::filter(results_2_cross,subject_id %in% right_subjs)
    #mod<-glmer(user_corr~delta_dist_div+(1+delta_dist_div|subject), family=binomial, data=sampdat)
    mod<-glm(user_corr~loc, family=binomial, data=sampdat)
    #myefs<-fixef(mod)
    myefs <- coef(mod)
    row<-data.frame(loc=unname(myefs[2]),N=i)
    df4 <- rbind(df4,row)
}

df4$N<-as.factor(df4$N)

p4<-ggplot(df4, aes(x=N, y=loc)) + 
  geom_violin()

p4
```


Number of participants vs. Beta estimates for  Var 1 = Econ
```{r N beta Econ}

df5<-data.frame(econ=c(),N_subjs=c())


for (i in mysubjs) {
   #sample i people from the list of subject 
    right_subjs<-sample(list_of_subjs,size=i,replace=FALSE)
    #filter only data from people selected above 
    sampdat<-dplyr::filter(results_2_cross,subject_id %in% right_subjs)
    #mod<-glmer(user_corr~delta_dist_div+(1+delta_dist_div|subject), family=binomial, data=sampdat)
    mod<-glm(user_corr~econ, family=binomial, data=sampdat)
    #myefs<-fixef(mod)
    myefs <- coef(mod)
    row<-data.frame(econ=unname(myefs[2]),N=i)
    df5 <- rbind(df5,row)
}

df5$N<-as.factor(df5$N)

p5<-ggplot(df5, aes(x=N, y=econ)) + 
  geom_violin()

p5
```


